importing of libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


In [ ]:
df=pd.read_csv("/content/housing_price.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                  15         5612            1283   
1    -114.47     34.40                  19         7650            1901   
2    -114.56     33.69                  17          720             174   
3    -114.57     33.64                  14         1501             337   
4    -114.57     33.57                  20         1454             326   

   population  households  median_income  median_house_value  
0        1015         472         1.4936               66900  
1        1129         463         1.8200               80100  
2         333         117         1.6509               85700  
3         515         226         3.1917               73400  
4         624         262         1.9250               65500

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  int64  
 3   total_rooms         17000 non-null  int64  
 4   total_bedrooms      17000 non-null  int64  
 5   population          17000 non-null  int64  
 6   households          17000 non-null  int64  
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  int64  
dtypes: float64(3), int64(6)
memory usage: 1.2 MB


In [ ]:
df.isnull()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
16995      False     False               False        False           False   
16996      False     False               False        False           False   
16997      False     False               False        False           False   
16998      False     False               False        False           False   
16999      False     False               False        False           False   

       population  households  median_income  median_house_value  
0           False       False          False               False  
1           False       False          False               False  
2           False       False          False               False  
3           False       False          False               False  
4           False       False          False               False  
...           ...         ...            ...                 ...  
16995       False       False          False               False  
16996       False       False          False               False  
16997       False       False          False               False  
16998       False       False          False               False  
16999       False       False          False               False  

[17000 rows x 9 columns]

In [ ]:
var=df.dropna()
var

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                  15         5612            1283   
1        -114.47     34.40                  19         7650            1901   
2        -114.56     33.69                  17          720             174   
3        -114.57     33.64                  14         1501             337   
4        -114.57     33.57                  20         1454             326   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                  52         2217             394   
16996    -124.27     40.69                  36         2349             528   
16997    -124.30     41.84                  17         2677             531   
16998    -124.30     41.80                  19         2672             552   
16999    -124.35     40.54                  52         1820             300   

       population  households  median_income  median_house_value  
0            1015         472         1.4936               66900  
1            1129         463         1.8200               80100  
2             333         117         1.6509               85700  
3             515         226         3.1917               73400  
4             624         262         1.9250               65500  
...           ...         ...            ...                 ...  
16995         907         369         2.3571              111400  
16996        1194         465         2.5179               79000  
16997        1244         456         3.0313              103600  
16998        1298         478         1.9797               85800  
16999         806         270         3.0147               94600  

[17000 rows x 9 columns]

#Split  data  into  two  DataFrames  x  and  y  based  on  dependent  and independent variables

In [ ]:
#Split  data  into  two  DataFrames  x  and  y  based  on  dependent  and independent variables
x=df[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income"]].values
y=df["median_house_value"].values
print("Independent varibles",x)
print("Dependent varibles:",y)


Independent varibles [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
Dependent varibles: [ 66900  80100  85700 ... 103600  85800  94600]


#Split x and y into train and test data set  based on test size as 0.2 and  random_state as10

In [ ]:
#Split x and y into train and test data set  based on test size as 0.2 and  random_state as10
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print("x_train and x_test data set shape",x_train.shape,x_test.shape)
print("y_train and y_test data set shape",y_train.shape,y_test.shape)

x_train and x_test data set shape (13600, 8) (3400, 8)
y_train and y_test data set shape (13600,) (3400,)


#Print R2 vallue,coefficient and intercept

In [ ]:
#fitting the model
regression=LinearRegression()
regression.fit(x_train,y_train)
regression.score(x_test,y_test)
#printing of r-squared values
print("R2 value:",regression.score(x_test,y_test))
print("coefficent:",regression.coef_)
print("intercept:",regression.intercept_)


R2 value: 0.6372145216134986
coefficent: [-4.28949835e+04 -4.24955906e+04  1.22379922e+03 -8.28460352e+00
  1.19134652e+02 -3.58341567e+01  3.71501205e+01  4.07498305e+04]
intercept: -3610498.035538576


#Compare actual and predicted values.

In [ ]:
#comparing of atual values and predicted values
y_pred=regression.predict(x_test)
var=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})
var.head(10)

Actual      Predicted
0  244900  298133.181186
1  253500  266409.730688
2  500001  270895.494077
3  324600  305671.522798
4  131000  218570.693325
5  150000  110470.695901
6   56000   95306.282241
7  279200  269672.416896
8  500001  616095.177996
9  154200  148639.422544

#Print the final summary


In [ ]:
import statsmodels.api as sm
x=df[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income"]].values
y=df["median_house_value"].values
x2=sm.add_constant(x)
est=sm.OLS(y,x2)
est2=est.fit()
print(est2.summary(1))


                            OLS Regression Results                            
Dep. Variable:                      1   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Thu, 19 Oct 2023   Prob (F-statistic):               0.00
Time:                        09:56:06   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0